version: '3.3'
services:
  flask:
    container_name: flaskAPI
    volumes:
      - /root/.aws/credentials:/root/.aws/credentials:ro
      - ./src:/app
    build: .
    ports:
      - "8000:5000"
  
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 443:8001
      - 80:8001
      - 8080:8001
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask