version: '3.3'
services:
  flask:
    container_name: card-maker
    image: card-maker:latest
    volumes:
      - /root/.aws:/root/.aws:ro
      - ./src:/app
    build: .
    ports:
      - "8000:5000"
    environment:
      - CM_INPUT=/app/services/blueprints/cardMaker/Input
      - CM_OUTPUT=/app/services/blueprints/cardMaker/Output
